using Newtonsoft.Json;

namespace cairn.Accounts.Auth
{
    /// <summary>DTO containing the informations about the tokens generated by Garda after a log in</summary>
    internal class UserAuthDTO
    {
        
        /// <summary>Access token used to access resources</summary>
        [JsonProperty("access_token")]
        public string AccessToken {get; set;}

        /// <summary>By default : Bearer</summary>
        [JsonProperty("token_type")]
        public string TokenType {get; set;}

        /// <summary>Generated token to refresh</summary>
        [JsonProperty("refresh_token")]
        public string RefreshToken {get; set;}

        /// <summary>Default constructor</summary>
        public UserAuthDTO()
        {
            
        }

        /// <summary>Constructor used for cloning</summary>
        public UserAuthDTO(UserAuthDTO baseAuth)
        {
            AccessToken = baseAuth.AccessToken;
            TokenType = baseAuth.TokenType;
            RefreshToken = baseAuth.RefreshToken;
        }
    }
}